# Generated by Django 5.0.3 on 2024-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.TextField(default=True, max_length=100)),
                ('lname', models.TextField(default=True, max_length=100)),
                ('email', models.EmailField(default=True, max_length=100)),
                ('message', models.TextField(default=True, max_length=1000)),
            ],
        ),
    ]
