# Generated by Django 5.0.4 on 2024-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('other', models.TextField(default='', max_length=100)),
                ('biketype', models.TextField(default='', max_length=250)),
                ('datetimef', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
